host: khemenu.thoth-station.ninja
tls_verify: false
requirements_format: pip

runtime_environments:
  - name: 'ubi8'
    operating_system:
      name: ubi
      version: "8.0"
    python_version: "3.8"
    recommendation_type: latest

managers:
  - name: version
    configuration:
      maintainers:
        - harshad16
        - goern
        - fridex
      assignees:
        - sesheta
      labels: [bot]
      changelog_file: false
  - name: update
    configuration:
      labels: [bot]
